### ISSUE TITLE
Clarification of proxy usage with included Laravel app?

### ISSUE THREAD

**Issue by mandofever78** [impxd/laravel-quasar-pwa-template#1]
Could you explain the usage of the proxy middleware for the dev configuration? 

Using 'npm run dev' I can successfully proxy api calls to a **separate** Laravel installation, and I can see that after running 'build' I can access api routes configured on the **included** Laravel installation. What I can't seem to do is access the **included** Laravel installation api routes while using 'npm run dev'. 

How do I serve the underlying Larvel install and access/develop it's api routes without having to run the build scripts with every update? What am I missing?

**Comment by impxd** [comment]
Hi there.
For each route that you want to use in dev mode you must modify the **config/index.js** file.
This is my config file:
```
    proxyTable: {
      '/api': {
        target: 'http://localhost:8000/api',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      },
      '/storage': {
        target: 'http://localhost:8000/storage',
        changeOrigin: true,
        pathRewrite: {
          '^/storage': ''
        }
      }
    }
```
The storage folder; that's another story.
All this setup is in a little mess.
The Quasar team is working in a new build system, i hope it'll be more friendly.

**Comment by mandofever78** [comment]
Thanks for the quick reply. Using your config for /api everything works if I run `npm run build` first to generate the app, then running `./artisan serve` followed by `npm run dev`. I'll keep tabs here and will eagerly await the new build system!

**Comment by impxd** [comment]
I made an update for the problem about run  first `npm run build` (basically it was just because the index.php file didn't exist) and the proxy tables.
If your service-worker.js doesn't work correctly check the updated file `webpack.prod.conf.js`

Cheers.

**Comment by mandofever78** [comment]
I tried the update and ran into some problems. I think it might be be due to this issue though I can't get anywhere with it: [https://stackoverflow.com/questions/31758901/laravel-5-change-public-path](url)

Here is the error i get when trying to run `artisan serve` regardless of before or after `run` or `build` processes:

```
[ErrorException]
  chdir(): No such file or directory (errno 2)
```

If I try to use `npm run dev` get this error:

```
node_modules/graceful-fs/polyfills.js:21
  chdir.call(process, d)
        ^
```

The only way I've made it through a successful test using `npm run dev` is this:

```
git clone
cp .env.exampl .env
composer install
npm install
artisan key:generate
rm -rf 'dist' (because `npm run build` throws an error if it exists) 
npm run build
ln -s dist public
artisan serve (separate tab)
npm run dev 
```

**Comment by impxd** [comment]
My bad. I deleted the public folder.

**Comment by mandofever78** [comment]
That was it, all is working as expected. Thanks!
